plugins: 
  - 
    - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "Features"
          - type: fix
            section: "Bug Fixes"
          - type: docs
            section: "Documentation"
          - type: perf
            section: "Performance improvements"
            hidden: false
          - type: test
            section: "Testing"
            hidden: false
          - type: ci
            section: "Build and continuous integration"
            hidden: true
          - type: build
            section: "Build and continuous integration"
            hidden: true
          - type: chore
            section: "Other changes"
          - type: style
            section: "Other changes"
            hidden: true
          - type: refactor
            section: "Other changes"
            hidden: true
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: revert
          release: minor
        - type: docs
          release: patch
        - type: style
          release: false
        - type: refactor
          release: false
        - type: test
          release: false
        - type: build
          release: false
        - type: ci
          release: false
        - type: chore
          release: false
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
### CUT ###
  - "@semantic-release/github"
  -
    - "@semantic-release/git"
    - assets:
      - '*.md'
      - '*.json'
  - "@semantic-release/npm"
  -
    - "@semantic-release/exec"
    - prepareCmd: |
        sed -ni '/### CUT ###*/q;p' .releaserc.yml
tagFormat: "${version}"
