# CONFIG
tagFormat: "${version}"
_types: &types
  - type: '*!'
    section: "BREAKING CHANGES"
    release: major
  - type: feat
    section: "Features"
    release: minor
  - type: chore
    scope: api-deps
    section: "Dependency updates"
    release: minor
  - type: chore
    scope: core-deps
    section: "Dependency updates"
    release: patch
  - type: fix
    section: "Bug Fixes"
    release: patch
  - type: docs
    section: "Documentation"
    release: patch
  - type: perf
    section: "Performance improvements"
    release: patch
  - type: revert
    section: "Revert previous changes"
    release: patch
  - type: test
    section: "Tests"
    release: false
  - type: ci
    section: "Build and continuous integration"
    release: false
  - type: build
    section: "Build and continuous integration"
    release: false
  - type: chore
    scope: deps
    section: "Dependency updates"
    release: false
  - type: chore
    section: "General maintenance"
    release: false
  - type: style
    section: "Style improvements"
    release: false
  - type: refactor
    section: "Refactoring"
    release: false
# ENDCONFIG
plugins:
  -
    - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      presetConfig:
        types: *types
      releaseRules:
        *types
### TEST ###
  -
    - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types: *types
  - "@semantic-release/changelog"
### CUT ###
  - "@semantic-release/npm"
  - "@semantic-release/github"
  -
    - "@semantic-release/git"
    - assets:
      - '*.md'
      - '*.json'
  -
    - "@semantic-release/exec"
    - prepareCmd: |
        mv .releaserc.json.pre .releaserc.json
