tagFormat: "${version}"
analyzeCommits:
  path: semantic-release-conventional-commits
  minorTypes:
    - feat
  patchTypes:
    - fix
    - doc
    - perf
plugins:
  -
    - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: "Features"
          - type: fix
            section: "Bug Fixes"
          - type: docs
            section: "Documentation"
          - type: perf
            section: "Performance improvements"
          - type: test
            section: "Testing"
          - type: ci
            section: "Build and continuous integration"
          - type: build
            section: "Build and continuous integration"
          - type: chore
            section: "Other changes"
          - type: style
            section: "Other changes"
          - type: refactor
            section: "Other changes" 
  - "@semantic-release/changelog"
### CUT ###
  - "@semantic-release/npm"
  - "@semantic-release/github"
  -
    - "@semantic-release/git"
    - assets:
      - '*.md'
      - '*.json'
  -
    - "@semantic-release/exec"
    - prepareCmd: |
        sed -ni '/### CUT ###*/q;p' .releaserc.yml
