name: Create a Release
on:
  push:
    branches-ignore:
      - 'renovate/**'
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
  workflow_dispatch:

jobs:
  release:
    if: >-
      github.event_name == 'push'
      && github.repository == 'DanySK/semantic-release-preconfigured-conventional-commits'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm install
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Debug
        if: failure()
        run: cat ~/.npm/_logs/*
