name: Create a Release
on:
  push:
    branches-ignore:
      - 'renovate/**'
    paths-ignore:
      - 'CHANGELOG.md'
      - 'LICENSE'
  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - name: Install
        run: npm install
      - name: Prepare the configuration
        uses: mikefarah/yq@v4.16.2
        with:
          cmd: >-
            sed -n '/### CUT ###*/q;p' .releaserc.yml | yq -o j -e eval > .releaserc.json.pre
      - name: Check the existence of the generated configuration
        run: |
          [ -s .releaserc.json.pre ] && jq -e < .releaserc.json.pre
      - name: Semantic Release
        if: >-
          github.event_name == 'push'
          && github.repository == 'DanySK/semantic-release-preconfigured-conventional-commits'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Debug
        if: failure()
        run: |
          cat .releaserc.json
          cat ~/.npm/_logs/*
